name: Generate Code (Stg)
on:
  workflow_dispatch:
    inputs:
      config_id:
        description: 'Business partner config ID'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    uses: ./.github/workflows/template_generate_code_create_pr.yaml
    with:
      config_id: ${{ github.event.inputs.config_id }}
      artifact_base_url: s3://bucket_stg
