name: '[Template] Release'
on:
  workflow_call:
    inputs:
      base_sha:
        description: 'Commit SHA of the base branch'
        required: true
        type: string
      head_sha:
        description: 'Commit SHA of the head branch'
        required: true
        type: string
      artifactory_url:
        description: 'Base URL for the deployment target'
        required: true
        type: string

jobs:
  release-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.head_sha }}
          fetch-depth: 0

      - name: Detect directory changes
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 #v47.0.0
        with:
          files: scaffold/**/*.py
          base_sha: ${{ inputs.base_sha }}
          sha: ${{ inputs.head_sha }}

      - name: Release to ${{ inputs.artifactory_url }}
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            FILENAME="$(basename "$file" .py)"
            IFS='-' read -r REPORT_ID REPORT_VERSION TIMESTAMP <<< $FILENAME
            DEST_PATH="${{ inputs.artifactory_url }}/${REPORT_ID}/${REPORT_VERSION}/${TIMESTAMP}/${FILENAME}.py"
            echo Releasing "$file" to "$DEST_PATH"
            mkdir -p "$(dirname "/tmp/$file")" && cp "$file" "/tmp/$file"
          done
